name: Python (venv) minimal sanity check

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show python
        run: python --version
